//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/prefabs/ARInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ARInputAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ARInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ARInputAction"",
    ""maps"": [
        {
            ""name"": ""TouchControl"",
            ""id"": ""d68fd082-d7c1-41ce-92b7-e574f3e269b4"",
            ""actions"": [
                {
                    ""name"": ""PrimaryTouch"",
                    ""type"": ""Value"",
                    ""id"": ""b5b5c4d9-5ff0-44b2-99ca-9f830479d55a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""83fe9370-64d8-4569-9ecb-59e9fb3bd369"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // TouchControl
        m_TouchControl = asset.FindActionMap("TouchControl", throwIfNotFound: true);
        m_TouchControl_PrimaryTouch = m_TouchControl.FindAction("PrimaryTouch", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // TouchControl
    private readonly InputActionMap m_TouchControl;
    private List<ITouchControlActions> m_TouchControlActionsCallbackInterfaces = new List<ITouchControlActions>();
    private readonly InputAction m_TouchControl_PrimaryTouch;
    public struct TouchControlActions
    {
        private @ARInputAction m_Wrapper;
        public TouchControlActions(@ARInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @PrimaryTouch => m_Wrapper.m_TouchControl_PrimaryTouch;
        public InputActionMap Get() { return m_Wrapper.m_TouchControl; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TouchControlActions set) { return set.Get(); }
        public void AddCallbacks(ITouchControlActions instance)
        {
            if (instance == null || m_Wrapper.m_TouchControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TouchControlActionsCallbackInterfaces.Add(instance);
            @PrimaryTouch.started += instance.OnPrimaryTouch;
            @PrimaryTouch.performed += instance.OnPrimaryTouch;
            @PrimaryTouch.canceled += instance.OnPrimaryTouch;
        }

        private void UnregisterCallbacks(ITouchControlActions instance)
        {
            @PrimaryTouch.started -= instance.OnPrimaryTouch;
            @PrimaryTouch.performed -= instance.OnPrimaryTouch;
            @PrimaryTouch.canceled -= instance.OnPrimaryTouch;
        }

        public void RemoveCallbacks(ITouchControlActions instance)
        {
            if (m_Wrapper.m_TouchControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITouchControlActions instance)
        {
            foreach (var item in m_Wrapper.m_TouchControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TouchControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TouchControlActions @TouchControl => new TouchControlActions(this);
    public interface ITouchControlActions
    {
        void OnPrimaryTouch(InputAction.CallbackContext context);
    }
}
